################################# Default configuration ###################
baseURL = "https://parrotsec.org"
title = "Parrot Security"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/fonts/fonts.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

############################# Navigation ##################################

[[menu.main]]
name = "Download"
URL = "download"
weight = 4

[[menu.main]]
name = "Community"
URL = "#community"
weight = 6

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 8

[[menu.main]]
name = "Documentation"
URL = "docs"
weight = 10

[[menu.main]]
name = "Get Involved"
URL = "contribute"
weight = 11

[[menu.main]]
name = "Team"
URL = "docs/team"
weight = 14

[[menu.main]]
name = "Partners"
URL = "docs/partners"
weight = 16

[[menu.main]]
name = "Donations & Gadgets"
URL = "donate"
weight = 16



############################# Default Parameters ##########################
[params]

version = "4.10"
mirror = "https://download.parrot.sh/parrot/iso/"

logo = "images/logo.png"
# Meta data
description = "Professional tools for Pentesters and Hackers"
author = "Parrot Security"
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

# comunity
[params.community]
enable = true
background = "images/backgrounds/world-map-poly.jpg"
title = "Official Forum"
content = "An awesome community is one click away. Receive assistence, share ideas and follow the development of the project."
btnURL = "https://community.parrotsec.org"
btnText = "Jump Aboard"
portalsTitle = "Community Links"
portalsDescription = "Telegram, Matrix, IRC, Facebook, Twitter, Instagram and more. All the official channels of our community."
portalsURL = "docs/community"
portalsURLtext = "Official Links"

# contribute
[params.contribute]
enable = true
background = "images/backgrounds/planet-poly.jpg"

# donate
[params.donate]
enable = true
background = "images/backgrounds/mountains-poly.jpg"

# footer
[params.footer]
copyright = "2013-2020 Lorenzo Faletra"
copyrightURL = "https://palinuro.dev"
copyright2 = "2020 Parrot Security CIC"
copyright2URL = "#you-are-already-here"


############################# social icons ##########################
[[params.social]]
icon = "/images/social/facebook.png"
link = "https://facebook.com/parrotsec"

[[params.social]]
icon = "/images/social/twitter.png"
link = "https://twitter.com/parrotsec"

[[params.social]]
icon = "/images/social/instagram.png"
link = "https://www.instagram.com/parrotproject/"

[[params.social]]
icon = "/images/social/telegram.png"
link = "https://t.me/parrotproject"

[[params.social]]
icon = "/images/social/wikipedia.png"
link = "https://en.wikipedia.org/wiki/Parrot_OS"

[[params.social]]
icon = "/images/social/distrowatch.png"
link = "https://distrowatch.com/parrot"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content"
weight = 1
home = "Home"
